language: elixir

elixir:
  - 1.4.0

services:
  - postgresql

before_script:
  - psql -c 'create database travis;' -U postgres  

addons:
  postgresql: "9.5"

env:
  global:
    - PSQL_USER=postgres
    - PSQL_DB=travis
