# TODO
# - Add NodeJS and install node, run brunch build and mix phoenix.digest!

FROM bitwalker/alpine-elixir

ENV HOME=/opt/app/ TERM=xterm

RUN apk update && \
    apk --no-cache --update add git make g++ && \
    rm -rf /var/cache/apk/*

# Install Hex+Rebar
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /opt/app

ENV MIX_ENV=prod

# Cache elixir deps
COPY mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

COPY . .

RUN mix release --env=prod --verbose
